export interface ReadableStoreMenuResponse {
  success: boolean;
  result?: (ResultEntity)[] | null;
}
export interface ResultEntity {}
// export interface ResultEntity {
//   Parmesan Bread Twists?: string | null;
//   Garlic Bread Twists?: string | null;
//   Stuffed Cheesy Bread?: string | null;
//   Stuffed Cheesy Bread with Spinach & Feta?: string | null;
//   Stuffed Cheesy Bread with Bacon & Jalapeno?: string | null;
//   16-Piece Parmesan Bread Bites?: string | null;
//   32-Piece Parmesan Bread Bites?: string | null;
//   Cinnamon Bread Twists?: string | null;
//   Domino's Marbled Cookie Brownie™?: string | null;
//   Chocolate Lava Crunch Cakes?: string | null;
//   20oz Bottle Coke®?: string | null;
//   20oz Bottle Fanta® Orange?: string | null;
//   20oz Bottle Sprite®?: string | null;
//   2-Liter Pibb Xtra®?: string | null;
//   2-Liter Coke®?: string | null;
//   2-Liter Diet Coke®?: string | null;
//   20oz Bottle Diet Coke®?: string | null;
//   2-Liter Fanta® Orange?: string | null;
//   2-Liter Sprite®?: string | null;
//   20oz Dasani® Bottle Water?: string | null;
//   20oz Bottle Cherry Coke®?: string | null;
//   20oz Bottle Pibb Xtra®?: string | null;
//   2-Liter Cherry Coke®?: string | null;
//   Classic Garden?: string | null;
//   Chicken Caesar?: string | null;
//   Build Your Own Pasta?: string | null;
//   Chicken Alfredo Pasta?: string | null;
//   Chicken Carbonara Pasta?: string | null;
//   Italian Sausage Marinara Pasta?: string | null;
//   Pasta Primavera?: string | null;
//   Build your Own BreadBowl Pasta?: string | null;
//   Chicken Alfredo BreadBowl Pasta?: string | null;
//   Chicken Carbonara BreadBowl Pasta?: string | null;
//   Italian Sausage Marinara BreadBowl Pasta?: string | null;
//   Pasta Primavera BreadBowl?: string | null;
//   Small (10") Hand Tossed Deluxe?: string | null;
//   Small (10") Hand Tossed MeatZZa?: string | null;
//   Small (10") Hand Tossed Buffalo Chicken?: string | null;
//   Small (10") Hand Tossed Memphis BBQ Chicken ?: string | null;
//   Small (10") Hand Tossed Cali Chicken Bacon Ranch?: string | null;
//   Small (10") Hand Tossed Wisconsin 6 Cheese Pizza?: string | null;
//   Small (10") Hand Tossed Philly Cheese Steak?: string | null;
//   Small (10") Hand Tossed Pacific Veggie?: string | null;
//   Small (10") Hand Tossed Ultimate Pepperoni?: string | null;
//   Small (10") Hand Tossed Honolulu Hawaiian?: string | null;
//   Small (10") Hand Tossed Pizza?: string | null;
//   Small (10") Hand Tossed ExtravaganZZa ?: string | null;
//   Medium (12") Hand Tossed Deluxe?: string | null;
//   Medium (12") Hand Tossed MeatZZa?: string | null;
//   Medium (12") Hand Tossed Buffalo Chicken?: string | null;
//   Medium (12") Hand Tossed Memphis BBQ Chicken ?: string | null;
//   Medium (12") Hand Tossed Cali Chicken Bacon Ranch?: string | null;
//   Medium (12") Hand Tossed Wisconsin 6 Cheese Pizza?: string | null;
//   Medium (12") Hand Tossed Philly Cheese Steak?: string | null;
//   Medium (12") Hand Tossed Pacific Veggie?: string | null;
//   Medium (12") Hand Tossed Ultimate Pepperoni?: string | null;
//   Medium (12") Hand Tossed Honolulu Hawaiian?: string | null;
//   Medium (12") Hand Tossed Pizza?: string | null;
//   Medium (12") Hand Tossed ExtravaganZZa ?: string | null;
//   Medium (12") Thin Deluxe?: string | null;
//   Medium (12") Thin MeatZZa?: string | null;
//   Medium (12") Thin Crust Buffalo Chicken?: string | null;
//   Medium (12") Thin Crust Memphis BBQ Chicken ?: string | null;
//   Medium (12") Thin Crust Cali Chicken Bacon Ranch?: string | null;
//   Medium (12") Thin Wisconsin 6 Cheese Pizza?: string | null;
//   Medium (12") Thin Philly Cheese Steak?: string | null;
//   Medium (12") Thin Crust Pacific Veggie?: string | null;
//   Medium (12") Thin Ultimate Pepperoni?: string | null;
//   Medium (12") Thin Crust Honolulu Hawaiian?: string | null;
//   Medium (12") Thin Pizza?: string | null;
//   Medium (12") Thin ExtravaganZZa ?: string | null;
//   Large (14") Brooklyn Deluxe?: string | null;
//   Large (14") Brooklyn MeatZZa?: string | null;
//   Large (14") Brooklyn Buffalo Chicken?: string | null;
//   Large (14") Brooklyn Memphis BBQ Chicken ?: string | null;
//   Large (14") Brooklyn Cali Chicken Bacon Ranch?: string | null;
//   Large (14") Brooklyn Wisconsin 6 Cheese Pizza?: string | null;
//   Large (14") Brooklyn Philly Cheese Steak?: string | null;
//   Large (14") Brooklyn Pacific Veggie?: string | null;
//   Large (14") Brooklyn Ultimate Pepperoni?: string | null;
//   Large (14") Brooklyn Honolulu Hawaiian?: string | null;
//   Large (14") Brooklyn Pizza?: string | null;
//   Large (14") Brooklyn ExtravaganZZa ?: string | null;
//   Large (14") Hand Tossed Deluxe?: string | null;
//   Large (14") Hand Tossed MeatZZa?: string | null;
//   Large (14") Hand Tossed Buffalo Chicken?: string | null;
//   Large (14") Hand Tossed Memphis BBQ Chicken ?: string | null;
//   Large (14") Hand Tossed Cali Chicken Bacon Ranch?: string | null;
//   Large (14") Hand Tossed Wisconsin 6 Cheese Pizza?: string | null;
//   Large (14") Hand Tossed Philly Cheese Steak?: string | null;
//   Large (14") Hand Tossed Pacific Veggie?: string | null;
//   Large (14") Hand Tossed Ultimate Pepperoni?: string | null;
//   Large (14") Hand Tossed Honolulu Hawaiian?: string | null;
//   Large (14") Hand Tossed Pizza?: string | null;
//   Large (14") Hand Tossed ExtravaganZZa ?: string | null;
//   Large (14") Thin Deluxe?: string | null;
//   Large (14") Thin MeatZZa?: string | null;
//   Large (14") Thin Crust Buffalo Chicken?: string | null;
//   Large (14") Thin Crust Memphis BBQ Chicken ?: string | null;
//   Large (14") Thin Crust Cali Chicken Bacon Ranch?: string | null;
//   Large (14") Thin Wisconsin 6 Cheese Pizza?: string | null;
//   Large (14") Thin Philly Cheese Steak?: string | null;
//   Large (14") Thin Crust Pacific Veggie?: string | null;
//   Large (14") Thin Ultimate Pepperoni?: string | null;
//   Large (14") Thin Crust Honolulu Hawaiian?: string | null;
//   Large (14") Thin Pizza?: string | null;
//   Large (14") Thin ExtravaganZZa ?: string | null;
//   X-Large (16") Brooklyn Deluxe?: string | null;
//   X-Large (16") Brooklyn MeatZZa?: string | null;
//   X-Large (16") Brooklyn Buffalo Chicken?: string | null;
//   X-Large (16") Brooklyn Memphis BBQ Chicken ?: string | null;
//   X-Large (16") Brooklyn Cali Chicken Bacon Ranch?: string | null;
//   X-Large (16") Brooklyn Wisconsin 6 Cheese Pizza?: string | null;
//   X-Large (16") Brooklyn Philly Cheese Steak?: string | null;
//   X-Large (16") Brooklyn Pacific Veggie?: string | null;
//   X-Large (16") Brooklyn Ultimate Pepperoni?: string | null;
//   X-Large (16") Brooklyn Honolulu Hawaiian?: string | null;
//   X-Large (16") Brooklyn Pizza?: string | null;
//   X-Large (16") Brooklyn ExtravaganZZa ?: string | null;
//   Small (10") Gluten Free Crust Deluxe?: string | null;
//   Small (10") Gluten Free Crust MeatZZa?: string | null;
//   Small (10") Gluten Free Crust Buffalo Chicken?: string | null;
//   Small (10") Gluten Free Crust Memphis BBQ Chicken ?: string | null;
//   Small (10") Gluten Free Crust Cali Chicken Bacon Ranch?: string | null;
//   Small (10") Gluten Free Crust Wisconsin 6 Cheese Pizza?: string | null;
//   Small (10") Gluten Free Crust Philly Cheese Steak?: string | null;
//   Small (10") Gluten Free Crust Pacific Veggie?: string | null;
//   Small (10") Gluten Free Crust Ultimate Pepperoni?: string | null;
//   Small (10") Gluten Free Crust Honolulu Hawaiian?: string | null;
//   Small (10") Gluten Free Crust Pizza?: string | null;
//   Small (10") Gluten Free Crust ExtravaganZZa ?: string | null;
//   Medium (12") Handmade Pan Deluxe?: string | null;
//   Medium (12") Handmade Pan MeatZZa?: string | null;
//   Medium (12") Handmade Pan Buffalo Chicken?: string | null;
//   Medium (12") Handmade Pan Memphis BBQ Chicken ?: string | null;
//   Medium (12") Handmade Pan Cali Chicken Bacon Ranch?: string | null;
//   Medium (12") Handmade Pan Wisconsin 6 Cheese Pizza?: string | null;
//   Medium (12") Handmade Pan Philly Cheese Steak?: string | null;
//   Medium (12") Handmade Pan Pacific Veggie?: string | null;
//   Medium (12") Handmade Pan Ultimate Pepperoni?: string | null;
//   Medium (12") Handmade Pan Honolulu Hawaiian?: string | null;
//   Medium (12") Handmade Pan Pizza?: string | null;
//   Medium (12") Handmade Pan ExtravaganZZa ?: string | null;
//   Small (10") Hand Tossed Spinach & Feta?: string | null;
//   Small (10") Gluten Free Crust Spinach & Feta?: string | null;
//   Medium (12") Hand Tossed Spinach & Feta?: string | null;
//   Medium (12") Thin Spinach & Feta?: string | null;
//   Medium (12") Handmade Pan Spinach & Feta?: string | null;
//   Large (14") Brooklyn Spinach & Feta?: string | null;
//   Large (14") Hand Tossed Spinach & Feta?: string | null;
//   Large (14") Thin Spinach & Feta?: string | null;
//   X-Large (16") Brooklyn Spinach & Feta?: string | null;
//   Chicken Bacon Ranch Sandwich?: string | null;
//   Chicken Parm Sandwich?: string | null;
//   Italian Sandwich?: string | null;
//   Philly Cheese Steak?: string | null;
//   Buffalo Chicken Sandwich?: string | null;
//   Chicken Habanero Sandwich?: string | null;
//   Mediterranean Veggie Sandwich?: string | null;
//   Parmesan Cheese Packets?: string | null;
//   Red Pepper Packets?: string | null;
//   Caesar Dressing?: string | null;
//   Ranch Dressing?: string | null;
//   Kicker Hot Dipping Cup?: string | null;
//   Sweet Mango Habanero Dipping Cup?: string | null;
//   BBQ Dipping Cup?: string | null;
//   Ranch Dipping Cup?: string | null;
//   Blue Cheese Dipping Cup?: string | null;
//   Garlic Dipping Cup?: string | null;
//   Icing Dipping Cup?: string | null;
//   Marinara Sauce Dipping Cup?: string | null;
//   St. Jude Donation?: string | null;
//   Balsamic?: string | null;
//   8-Piece Boneless Chicken?: string | null;
//   8-piece Hot Wings?: string | null;
//   8-Piece BBQ Wings?: string | null;
//   8-piece Plain Wings?: string | null;
//   8-Piece Sweet Mango Habanero Wings?: string | null;
//   14-Piece Boneless Chicken?: string | null;
//   14-piece Hot Wings?: string | null;
//   14-Piece BBQ Wings?: string | null;
//   14-piece Plain Wings?: string | null;
//   14-Piece Sweet Mango Habanero Wings?: string | null;
//   40-Piece Boneless Chicken?: string | null;
//   40-piece Hot Wings?: string | null;
//   40-Piece BBQ Wings?: string | null;
//   40-piece Plain Wings?: string | null;
//   40-Piece Sweet Mango Habanero Wings?: string | null;
//   Specialty Chicken – Crispy Bacon & Tomato?: string | null;
//   Specialty Chicken – Classic Hot Buffalo?: string | null;
//   Specialty Chicken – Spicy Jalapeno - Pineapple?: string | null;
//   Specialty Chicken – Sweet BBQ Bacon?: string | null;
// }
